### ISSUE TITLE
descriptor.proto missing

### ISSUE THREAD

**Issue by JoshOrndorff** [JoshOrndorff/RChain-API#12]
When running the integration test I get
```
$ node rnodeAPI.js localhost 40401
/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:4720
                            throw Error("failed to import '"+importFilename+"' in '"+filename+"': file not found");
                            ^

Error: failed to import '/home/joshy/ProgrammingProjects/RChain-API/protobuf/scalapb/descriptor.proto' in '/home/joshy/ProgrammingProjects/RChain-API/protobuf/scalapb/scalapb.proto': file not found
    at Builder.ProtoBuf.Builder.BuilderPrototype.import (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:4720:35)
    at Builder.ProtoBuf.Builder.BuilderPrototype.import (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:4724:43)
    at Object.ProtoBuf.loadJson (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:5225:26)
    at Object.ProtoBuf.loadProto (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:5128:25)
    at Object.ProtoBuf.loadProtoFile (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:5174:52)
    at Object.load (/home/joshy/ProgrammingProjects/RChain-API/node_modules/grpc/index.js:136:26)
    at Object.deprecated [as load] (internal/util.js:67:15)
    at RNode (/home/joshy/ProgrammingProjects/RChain-API/rnodeAPI.js:40:22)
    at integrationTest (/home/joshy/ProgrammingProjects/RChain-API/rnodeAPI.js:332:14)
    at Object.<anonymous> (/home/joshy/ProgrammingProjects/RChain-API/rnodeAPI.js:389:3)
```

Indeed `scalapb.proto` does try to import `descriptor.proto` on line 12. I guess maybe the makefile needs updating?

**Comment by JoshOrndorff** [comment]
I got my branches crossed or something, because this is not a real issue. Cannot reproduce.
